//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MUSHclient.rc
//
#define ID_SEARCH_FIND                  3
#define ID_SEARCH_FINDNEXT              8
#define ID_SYS_SAVE                     0x0010
#define ID_SYS_SAVE_AS                  0x0020
#define ID_SEARCH_REPLACE               40
#define IDD_ABOUTBOX                    100
#define CG_IDS_TIPOFTHEDAY              101
#define IDR_TRIGGERIMAGES               101
#define IDR_ACTIVITYIMAGES              101
#define IDB_SPLASH                      102
#define IDB_LIGHTBULB                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_TIP                         105
#define ID_FINGER_CURSOR                106
#define CG_IDS_TIPOFTHEDAYMENU          107
#define CG_IDS_DIDYOUKNOW               108
#define CG_IDS_FILE_ABSENT              109
#define CG_IDP_FILE_CORRUPT             110
#define CG_IDS_TIPOFTHEDAYHELP          111
#define IDS_PROPSHT_CAPTION             112
#define IDD_REGPAGE1                    113
#define IDS_OPEN_WORLD_FILTER           117
#define IDS_OPEN_WORLD_TITLE            118
#define CG_IDR_POPUP_SEND_VIEW          124
#define CG_IDR_POPUP_MUSHVIEW           125
#define CG_IDR_POPUP_MAIN_FRAME         126
#define CG_IDR_POPUP_ACTIVITY_VIEW      127
#define ID_VIEW_GAME_TOOLBAR            128
#define IDR_MAINFRAME                   128
#define IDR_MUSHCLTYPE                  129
#define IDR_NORMALTYPE                  130
#define IDR_ACTIVITYTYPE                131
#define IDD_COMMAND_HISTORY             132
#define IDD_PREFS_P1                    133
#define IDD_PREFS_P2                    134
#define IDD_PREFS_P3                    135
#define IDD_PASSWORD                    136
#define IDD_PREFS_P4                    137
#define IDD_PREFS_P5                    138
#define IDD_EDIT_STRING                 139
#define IDD_PREFS_P6                    140
#define IDD_EDIT_MACRO                  141
#define IDS_PROPSHT_CAPTION1            142
#define IDD_NEW_MESSAGES                143
#define IDD_PREFS_P7                    144
#define IDD_PREFS_P8                    145
#define IDD_PREFS_P9                    146
#define IDD_EDIT_ALIAS                  147
#define IDD_EDIT_TRIGGER                148
#define IDD_TEST_COMMAND                149
#define IDD_TEST_TRIGGER                150
#define IDD_TEST_RESULT                 151
#define IDD_PREFS_P10                   152
#define IDD_PREFS_P11                   153
#define IDD_WELCOME                     154
#define IDD_PREFS_P12                   155
#define IDD_CONNECTING                  156
#define IDD_REGPAGE2                    158
#define IDD_REGPAGE3                    159
#define IDD_REGPAGE4                    160
#define IDD_REGPAGE5                    161
#define IDD_REGPAGE6                    162
#define IDD_REGPAGE7                    163
#define IDD_REGPAGE8                    164
#define IDD_REGPAGE9                    165
#define IDD_REGPAGE10                   166
#define IDD_REGPAGE11                   167
#define IDD_REGPAGE12                   168
#define IDD_REGPAGE13                   169
#define IDD_REGPAGE14                   170
#define IDD_REGPAGE15                   171
#define IDD_REGPAGE16                   172
#define IDD_PREFS_P13                   173
#define IDD_PREFS_P14                   174
#define IDD_PASTE_PREAMBLES             175
#define IDD_PREFS_P15                   176
#define IDR_CREDITS                     177
#define IDD_EDIT_TIMER                  178
#define IDD_GLOBAL_PREFSP1              179
#define IDD_GLOBAL_PREFSP2              180
#define IDD_GLOBAL_PREFSP3              181
#define IDD_GLOBAL_PREFSP4              182
#define IDR_GAME_TOOLBAR                183
#define IDD_GLOBAL_PREFSP5              184
#define IDD_GLOBAL_PREFSP6              185
#define IDD_IMMEDIATE                   186
#define IDD_PREFS_P17                   187
#define IDD_PREFS_P18                   188
#define IDD_EDIT_VARIABLE               189
#define IDD_FIND                        190
#define CG_IDD_PROGRESS                 191
#define CG_IDS_PROGRESS_CAPTION         192
#define IDD_PREFS_P19                   192
#define IDD_PREFS_P20                   193
#define IDD_GLOBAL_PREFSP7              194
#define IDD_MISSING_ENTRY_POINTS        195
#define IDD_UNREGISTERED_DELAY          196
#define IDD_PREFS_P21                   197
#define IDR_ACTIVITY_TOOLBAR            198
#define IDD_CONFIGURATION               200
#define IDD_EDIT_MUD                    201
#define IDD_GLOBAL_PREFSP8              202
#define IDD_CREDITS                     203
#define IDD_REGPAGE17                   204
#define IDD_QUICK_CONNECT               205
#define IDR_MAINFRAME2                  206
#define IDD_LINE_COUNT                  208
#define IDD_WELCOME1                    209
#define IDD_PREFS_P16                   210
#define IDD_TAB_COMPLETION_DEFAULTS_DLG 211
#define IDD_GLOBAL_CHANGE               212
#define IDD_PREFERENCES                 215
#define IDD_PREFS_P0                    216
#define ID_RECALL_WINDOW                217
#define IDD_RECALL                      218
#define IDD_SEND_TO_ALL                 219
#define IDR_COLOUR_POPUP                221
#define IDD_TEXT_ATTRIBUTES             223
#define IDD_SCRIPT_ERROR                224
#define IDD_GENERATED_NAME              230
#define IDD_GLOBAL_PREFSP9              231
#define IDD_GOTO                        232
#define IDD_GLOBAL_PREFSP10             233
#define IDR_NON_MENU_ITEMS              234
#define IDD_CHOOSE_NOTEPAD              240
#define IDB_NICK                        243
#define IDD_WINSOCK_INFO                244
#define IDD_MAPPER                      245
#define IDD_MAP_MOVE                    246
#define IDD_EDIT                        247
#define IDD_ASCII_ART                   248
#define IDD_COMMAND_OPTIONS             249
#define IDR_LICENSE                     252
#define IDR_MXP_MENU                    254
#define IDD_MXP_SCRIPTS                 255
#define IDD_DEBUG_INPUT                 256
#define IDD_COLOUR_PICKER               257
#define IDD_PREFS_P22                   258
#define IDB_ACTIVITY_TOOLBAR_1          263
#define IDB_ACTIVITY_TOOLBAR_2          264
#define IDB_ACTIVITY_TOOLBAR_3          265
#define IDB_ACTIVITY_TOOLBAR_4          266
#define IDB_ACTIVITY_TOOLBAR_5          267
#define IDB_ACTIVITY_TOOLBAR_0          268
#define IDD_IMPORT_XML                  272
#define IDD_PLUGINS                     273
#define IDD_MAP_COMMENT                 277
#define IDR_SUBSTITUTION                278
#define IDD_INFO                        280
#define IDD_CHAT_LIST                   284
#define IDD_CHAT_CALL                   285
#define IDD_CHAT_DETAILS                286
#define IDD_PROXY_PASSWORD              287
#define IDI_ICON1                       288
#define IDI_ICON2                       289
#define IDI_ICON3                       290
#define IDI_ICON4                       291
#define IDI_ICON5                       292
#define IDI_ICON6                       293
#define IDI_ICON7                       294
#define IDI_ICON8                       295
#define IDI_ICON9                       296
#define IDI_ICON10                      297
#define IDR_RIGHT_TRAY_MENU             298
#define IDR_MULTIPLE_ASTERISKS          300
#define ID_GETTING_STARTED              301
#define IDD_REGEXP_PROBLEM              301
#define IDS_PROPSHT_CAPTION2            304
#define IDD_PLUGINWIZARDPAGE1           305
#define IDD_PLUGINWIZARDPAGE2           306
#define IDD_PLUGINWIZARDPAGE3           307
#define IDD_PLUGINWIZARDPAGE4           308
#define IDD_PLUGINWIZARDPAGE5           309
#define IDD_PLUGINWIZARDPAGE6           310
#define IDD_PLUGINWIZARDPAGE7           311
#define IDD_PLUGINWIZARDPAGE8           312
#define IDD_EDIT_MULTILINE              313
#define IDD_PREFS_P23                   314
#define IDD_CHAT_SAY_ALL                315
#define IDD_CHAT_EMOTE_ALL              316
#define IDD_GLOBAL_PREFSP11             317
#define IDD_GLOBAL_PREFSP12             318
#define IDR_PANETYPE                    319
#define IDD_GLOBAL_PREFSP13             319
#define IDR_LUA_SCRIPT                  320
#define IDR_REGEXP_MENU                 320
#define IDD_HIGHLIGHT                   323
#define IDD_GENERATE_UNIQUE_ID          325
#define IDD_MULTILINE_TRIGGER           327
#define IDD_LUA_INPUTBOX                329
#define IDD_LUA_CHOOSE                  330
#define IDD_LUA_CHOOSE_LIST             331
#define IDD_FUNCTION_LIST               332
#define IDD_LUA_GSUB                    333
#define IDD_COMPLETE_WORD               334
#define IDD_LUA_INPUTEDIT               335
#define IDD_KEY_NAME                    336
#define IDD_LUA_CHOOSE_LIST_MULTI       337
#define IDD_LUA_DEBUG                   338
#define IDD_SPELLCHECK_DIALOG           340
#define IDD_INSERT_UNICODE              342
#define IDC_MY_IBEAM                    349
#define ID_IGNORE_BTN                   1001
#define ID_LEX_CONTENTS_CB              1001
#define ID_IGNORE_ALL_BTN               1002
#define ID_LEX_FILES_CB                 1002
#define ID_CHANGE_BTN                   1003
#define ID_LEX_ADD_FILE_BTN             1003
#define IDC_LINE_NUMBER                 1003
#define ID_CHANGE_ALL_BTN               1004
#define ID_LEX_DEL_FILE_BTN             1004
#define ID_ADD_TO_LEX_BTN               1005
#define ID_SUGGEST_BTN                  1006
#define ID_UNDO_BTN                     1007
#define ID_SUGGEST_LIST                 1009
#define ID_PROBLEM_LBL                  1011
#define ID_PROBLEM_WORD_EDT             1012
#define ID_IGN_LEX_CB                   1013
#define ID_EDIT_LEX_BTN                 1014
#define ID_LEX_ADD_WORD_BTN             1014
#define ID_LEX_DEL_WORD_BTN             1015
#define ID_LEX_NEW_FILE_BTN             1016
#define IDC_IGNORE_CAPS_CHK             1021
#define IDC_REPORT_DOUBLED_WORDS_CHK    1022
#define ID_LANGUAGE_CB                  1023
#define ID_IMPORT_BTN                   1024
#define ID_EXPORT_BTN                   1025
#define IDC_IGNORE_MIXED_DIGITS_CHK     1025
#define ID_FILE_NAME_EDIT               1027
#define ID_BROWSE_BTN                   1028
#define IDC_IGNORE_ALL_CAPS_CHK         1028
#define ID_LANG_TEXT                    1029
#define ID_OPTIONS_BTN                  1031
#define ID_SUGGESTIONS_LBL              1033
#define ID_ADD_WORDS_LBL                1034
#define ID_WORDS_LBL                    1035
#define ID_FILES_LBL                    1036
#define ID_LANGUAGE_LBL                 1037
#define ID_FILE_NAME_LBL                1039
#define IDC_SELECT_COLOUR               1039
#define IDC_CASE_SENSITIVE_CHK          1041
#define IDC_PHONETIC_SUGG_CHK           1042
#define IDC_SUGGEST_SPLIT_WORDS_CHK     1043
#define IDC_IGNORE_MIXED_CASE_CHK       1044
#define IDC_TYPO_SUGG_CHK               1045
#define IDC_IGNORE_DOMAIN_NAMES_CHK     1046
#define IDC_COLOUR_SWATCH               1048
#define IDC_CONTEXT_EDT                 1050
#define IDC_AUTO_CORRECT_CHK            1050
#define IDC_SUGG_DEPTH_LOW_RB           1051
#define IDC_SUGG_DEPTH_MED_RB           1052
#define IDC_SUGG_DEPTH_HI_RB            1053
#define ID_HELP_BTN                     1055
#define ID_LEX_OTHER_WORD_EDT           1057
#define ID_LEX_ACTION_CB                1058
#define IDC_DICT_LANG_CBO               1059
#define IDC_TRY_AGAIN                   1639
#define IDC_LOG_OUTPUT                  2000
#define IDC_HUE                         2001
#define IDC_SATURATION                  2002
#define IDC_BRIGHTNESS                  2003
#define IDC_LINES                       2004
#define IDC_BULB                        2005
#define IDC_CHANNEL                     2006
#define IDC_STARTUP                     2007
#define IDC_WRAP_COLUMN                 2008
#define IDC_SERVER                      2009
#define IDC_NEXTTIP                     2010
#define IDC_MUSH_NAME                   2011
#define CG_IDC_PROGDLG_PROGRESS         2012
#define IDC_CHARACTER                   2013
#define IDC_TIPSTRING                   2014
#define CG_IDC_PROGDLG_PERCENT          2015
#define IDC_PASSWORD                    2016
#define CG_IDC_PROGDLG_STATUS           2017
#define IDC_WRAP_LINES                  2018
#define IDC_TIMESTAMPS                  2019
#define IDC_LOG_INPUT                   2020
#define IDC_COMMANDS                    2021
#define IDC_CONNECT_NOW                 2022
#define IDC_WRAP_OUTPUT                 2023
#define IDC_CHOOSE_FONT                 2024
#define IDC_BLACK                       2025
#define IDC_RED                         2026
#define IDC_GREEN                       2027
#define IDC_YELLOW                      2028
#define IDC_BLUE                        2029
#define IDC_MAGENTA                     2030
#define IDC_CYAN                        2031
#define IDC_WHITE                       2032
#define IDC_BLACK_BOLD                  2033
#define IDC_RED_BOLD                    2034
#define IDC_REMOVE_CHANNELS1            2035
#define IDC_GREEN_BOLD                  2036
#define IDC_REMOVE_CHANNELS2            2037
#define IDC_YELLOW_BOLD                 2038
#define IDC_REMOVE_PAGES                2039
#define IDC_BLUE_BOLD                   2040
#define IDC_REMOVE_WHISPERS             2041
#define IDC_MAGENTA_BOLD                2042
#define IDC_REMOVE_SET                  2043
#define IDC_CYAN_BOLD                   2044
#define IDC_REMOVE_MAIL                 2045
#define IDC_WHITE_BOLD                  2046
#define IDC_REMOVE_GAME                 2047
#define IDC_PAGE_COLOUR                 2048
#define IDC_WHISPER_COLOUR              2049
#define IDC_STRINGS_LIST                2050
#define IDC_MAIL_COLOUR                 2051
#define IDC_EDIT_STRING                 2052
#define IDC_STRING_TYPE                 2053
#define IDC_GAME_COLOUR                 2054
#define IDC_LOAD_STRING                 2055
#define IDC_MATCH_ON                    2056
#define IDC_SAVE_STRING                 2057
#define IDC_CHAT_COLOUR                 2058
#define IDC_EDIT_MACRO                  2059
#define IDC_MACROS_LIST                 2060
#define IDC_MACRO_TYPE                  2061
#define IDC_LOAD_MACRO                  2062
#define IDC_SEND_IMMEDIATELY            2063
#define IDC_SAVE_MACRO                  2064
#define IDC_MACRO_TEXT                  2065
#define IDC_MATCH_WIDTH                 2066
#define IDC_ACTIVITY_LIST               2067
#define IDC_OK                          2068
#define IDC_CLOSE                       2069
#define IDC_ADD_ALIAS                   2070
#define IDC_CHANGE_ALIAS                2071
#define IDC_DELETE_ALIAS                2072
#define IDC_ADD_TRIGGER                 2073
#define IDC_LOAD_ALIAS                  2074
#define IDC_CHANGE_TRIGGER              2075
#define IDC_SAVE_ALIAS                  2076
#define IDC_DELETE_TRIGGER              2077
#define IDC_ENABLE_SPEED_WALK           2078
#define IDC_LOAD_TRIGGER                2079
#define IDC_SPEED_WALK_PREFIX           2080
#define IDC_SAVE_TRIGGER                2081
#define IDC_FIND_WHAT                   2082
#define IDC_ENABLE_COMMAND_STACKING     2083
#define IDC_CONNECT_TEXT                2084
#define IDC_COMMAND_STACK_CHARACTER     2085
#define IDC_TRIGGERS_LIST               2086
#define IDC_ALIASES_LIST                2087
#define IDC_ALIAS_CONTENTS              2088
#define IDC_ALIAS_NAME                  2089
#define IDC_IGNORE_CASE                 2090
#define IDC_TRIGGER                     2091
#define IDC_TRIGGER_CONTENTS            2092
#define IDC_TEST_COMMAND                2093
#define IDC_TEST_TRIGGER                2094
#define IDC_TEST_RESULT                 2095
#define IDC_ENABLE_ALIASES              2096
#define IDC_ENABLE_TRIGGERS             2097
#define IDC_MATCH_TYPE                  2098
#define IDC_ANYWHERE                    2099
#define IDC_EXACTLY                     2100
#define IDC_TRIGGER_COLOUR              2101
#define IDC_LOAD_COLOURS                2102
#define IDC_SEND_TO                     2103
#define IDC_MATCH_TEXT_COLOUR           2104
#define IDC_SAVE_COLOURS                2105
#define IDC_SOUND_PATH                  2106
#define IDC_ALL_LIGHTER                 2107
#define IDC_SOUND_PATH2                 2107
#define IDC_BROWSE_SOUNDS               2108
#define IDC_ALL_DARKER                  2109
#define IDC_BROWSE_SOUNDS2              2109
#define IDC_NO_SOUND                    2110
#define IDC_ALL_MORE_COLOUR             2111
#define IDC_TEST_SOUND                  2112
#define IDC_ALL_LESS_COLOUR             2113
#define IDC_TEST_SOUND2                 2113
#define IDC_HELPBUTTON                  2114
#define IDC_ECHO_INPUT                  2115
#define IDC_MATCH_BACK_COLOUR           2116
#define IDC_ECHO_COLOUR                 2117
#define IDC_ENABLE_BEEPS                2118
#define IDC_ENABLE_TRIGGERS_SOUNDS      2119
#define IDC_FILE_PREAMBLE               2120
#define IDC_LINE_PREAMBLE               2121
#define IDC_LINE_POSTAMBLE              2122
#define IDC_NOTES                       2123
#define IDC_FILE_POSTAMBLE              2124
#define IDC_LOAD_NOTES                  2125
#define IDC_SAVE_NOTES                  2126
#define IDC_OMIT_FROM_LOG               2127
#define IDC_KEYPAD_7                    2128
#define IDC_KEYPAD_8                    2129
#define IDC_KEYPAD_9                    2130
#define IDC_KEYPAD_PLUS                 2131
#define IDC_KEYPAD_4                    2132
#define IDC_KEYPAD_5                    2133
#define IDC_KEYPAD_6                    2134
#define IDC_ENABLE_KEYPAD               2135
#define IDC_KEYPAD_1                    2136
#define IDC_SEND_TYPE                   2137
#define IDC_KEYPAD_2                    2138
#define IDC_RADIO2                      2139
#define IDC_KEYPAD_3                    2140
#define IDC_RADIO3                      2141
#define IDC_KEYPAD_0                    2142
#define IDC_INDENT_PARAS                2143
#define IDC_RADIO4                      2144
#define IDC_NAWS                        2145
#define IDC_KEYPAD_DOT                  2146
#define IDC_BLACK_SWATCH                2147
#define IDC_KEYPAD_SLASH                2148
#define IDC_RED_SWATCH                  2149
#define IDC_KEYPAD_STAR                 2150
#define IDC_GREEN_SWATCH                2151
#define IDC_PAGES_SWATCH                2152
#define IDC_KEYPAD_DASH                 2153
#define IDC_YELLOW_SWATCH               2154
#define IDC_WHISPERS_SWATCH             2155
#define IDC_INPUT_SWATCH                2156
#define IDC_BLUE_SWATCH                 2157
#define IDC_MAIL_SWATCH                 2158
#define IDC_TRIGGER_SWATCH              2159
#define IDC_TEXT_SWATCH                 2160
#define IDC_SCRIPT_BACKGROUND_SWATCH    2161
#define IDC_RGB_BACKGROUND_SWATCH       2161
#define IDC_MAGENTA_SWATCH              2162
#define IDC_GAME_SWATCH                 2163
#define IDC_BACKGROUND_SWATCH           2164
#define IDC_TRIGGER_SWATCH2             2165
#define IDC_CYAN_SWATCH                 2166
#define IDC_CHAT_SWATCH                 2167
#define IDC_TEXT_COLOUR                 2168
#define IDC_INPUT_SWATCH2               2169
#define IDC_TEXT_COLOUR_RGB             2169
#define IDC_WHITE_SWATCH                2170
#define IDC_BACKGROUND_COLOUR           2171
#define IDC_BLACK_SWATCH_BOLD           2172
#define IDC_INPUT_FONT                  2173
#define IDC_RELOAD_OPTION               2174
#define IDC_RED_SWATCH_BOLD             2175
#define IDC_FONT_NAME                   2176
#define IDC_GREEN_SWATCH_BOLD           2177
#define IDC_TRIGGER_NAME                2178
#define IDC_YELLOW_SWATCH_BOLD          2179
#define IDC_OMIT_FROM_OUTPUT            2180
#define IDC_BLUE_SWATCH_BOLD            2181
#define IDC_ENABLED                     2182
#define IDC_MAGENTA_SWATCH_BOLD         2183
#define IDC_KEEP_EVALUATING             2184
#define IDC_CYAN_SWATCH_BOLD            2185
#define IDC_COLOUR_LABEL                2186
#define IDC_WHITE_SWATCH_BOLD           2187
#define IDC_YES_NO                      2188
#define IDC_USER_NAME                   2189
#define IDC_SWATCH_CUSTOM1              2190
#define IDC_PERSONAL_CODE               2191
#define IDC_SWATCH_CUSTOM2              2192
#define IDC_EMAIL_ADDRESS               2193
#define IDC_SWATCH_CUSTOM3              2194
#define IDC_POSTAL_ADDRESS              2195
#define IDC_SWATCH_CUSTOM4              2196
#define IDC_ZIP_CODE                    2197
#define IDC_SWATCH_CUSTOM5              2198
#define IDC_COUNTRY                     2199
#define IDC_SWATCH_CUSTOM6              2200
#define IDC_CREDIT_CARD_NUMBER          2201
#define IDC_SWATCH_CUSTOM7              2202
#define IDC_EXPIRY_DATE                 2203
#define IDC_SWATCH_CUSTOM8              2204
#define IDC_NAME_ON_CARD                2205
#define IDC_SWATCH_CUSTOM9              2206
#define IDC_BUTTON1                     2207
#define IDC_STANDARD_PREAMBLE           2207
#define IDC_FILE_DIR_BROWSE             2207
#define IDC_CALL                        2207
#define IDC_COPY_TO_CUSTOM              2207
#define IDC_PROXY_SERVER_PASSWORD       2207
#define IDC_CHOOSE_ICON_FILE            2207
#define IDC_ADJUST_TO_WIDTH             2207
#define IDC_SPECIAL                     2207
#define IDC_DEFAULTS                    2207
#define IDC_REGEXP_BUTTON               2207
#define IDC_COPY_NAME                   2207
#define IDC_FUNCTION_LIST               2207
#define IDC_EDIT_FILTER                 2207
#define IDC_NEW_SCRIPT                  2207
#define IDC_SHOW_UPS                    2207
#define IDC_REGEXP_HELP                 2207
#define IDC_CALCULATE_MEMORY            2207
#define IDC_OPEN_EXISTING               2208
#define IDC_NORMAL_LIGHTER              2209
#define IDC_NOTEPAD                     2210
#define IDC_REVERSE                     2211
#define IDC_REMOVE_ALL                  2212
#define IDC_EDIT                        2213
#define IDC_ADD_CURRENT_WORLD           2214
#define IDC_EDIT_REPLACE                2214
#define IDC_BROWSE_NAME                 2215
#define IDC_LICENSE                     2216
#define IDC_LINE_INFO                   2217
#define IDC_KEYBOARD_PREFS              2218
#define IDC_MXP_SCRIPTS                 2219
#define IDC_RESET_TAGS                  2220
#define IDC_PASTE                       2221
#define IDC_CLIPBOARD                   2222
#define IDC_SHOW_DESCRIPTION            2223
#define IDC_SWATCH_CUSTOM17             2224
#define IDC_NORMAL_DARKER               2225
#define IDC_REMOVE_LAST                 2226
#define IDC_EDIT2                       2227
#define IDC_PASTE_PREAMBLE              2228
#define IDC_BOLD_LIGHTER                2229
#define IDC_SELECT7                     2230
#define IDC_BOLD_DARKER                 2231
#define IDC_SWATCH_CUSTOM18             2232
#define IDC_PASTELINE_PREAMBLE          2233
#define IDC_SELECT8                     2234
#define IDC_SWATCH_CUSTOM19             2235
#define IDC_PASTELINE_POSTAMBLE         2236
#define IDC_SELECT9                     2237
#define IDC_SWATCH_CUSTOM20             2238
#define IDC_PASTE_POSTAMBLE             2239
#define IDC_SWATCH_CUSTOM21             2240
#define IDC_SWATCH_CUSTOM22             2241
#define IDC_PASTE_MESSAGE               2242
#define IDC_SWATCH_CUSTOM23             2243
#define IDC_ARGUMENT                    2244
#define IDC_SWATCH_CUSTOM24             2245
#define IDC_SWATCH_CUSTOM25             2246
#define IDC_SWATCH_CUSTOM26             2247
#define IDC_WILDCARD_CLIPBOARD          2248
#define IDC_SWATCH_CUSTOM27             2249
#define IDC_USE_CLIPBOARD               2250
#define IDC_SWATCH_CUSTOM28             2251
#define IDC_ALIAS_LABEL                 2252
#define IDC_SWATCH_CUSTOM29             2253
#define IDC_HISTORY_LINES               2254
#define IDC_SWATCH_CUSTOM30             2255
#define IDC_IP_ADDRESS                  2256
#define IDC_SWATCH_CUSTOM31             2257
#define IDC_BUFFER_LINES                2258
#define IDC_SWATCH_CUSTOM32             2259
#define IDC_OUTPUT_MEMORY               2260
#define IDC_CONNECTION_TIME             2261
#define IDC_CONNECTION_DURATION         2262
#define IDC_TRIGGERS                    2263
#define IDC_BUTTON_AT                   2264
#define IDC_ALIASES                     2265
#define IDC_AT_HOUR                     2266
#define IDC_AT_MINUTE                   2267
#define IDC_MACROS                      2268
#define IDC_COMPRESSION_RATIO           2269
#define IDC_VARIABLES                   2270
#define IDC_AT_SECOND                   2271
#define IDC_COLOURS                     2272
#define IDC_BYTES_RECEIVED              2273
#define IDC_KEYPAD                      2274
#define IDC_INTERVAL_HOUR               2275
#define IDC_PRINTING                    2276
#define IDC_BYTES_SENT                  2277
#define IDC_INTERVAL_MINUTE             2278
#define IDC_TIMERS                      2279
#define IDC_INTERVAL_SECOND             2280
#define IDC_OFFSET_HOUR                 2281
#define IDC_OFFSET_MINUTE               2282
#define IDC_OFFSET_SECOND               2283
#define IDC_TIMER_CONTENTS              2284
#define IDC_TIMER_LABEL                 2285
#define IDC_TIMERS_LIST                 2286
#define IDC_ENABLE_TIMERS               2287
#define IDC_RESET_TIMERS                2288
#define IDC_ADD_TIMER                   2289
#define IDC_CHANGE_TIMER                2290
#define IDC_DELETE_TIMER                2291
#define IDC_LOAD_TIMERS                 2292
#define IDC_SAVE_TIMERS                 2293
#define IDC_BUTTON_EVERY                2294
#define IDC_SPIN_AT_HOUR                2295
#define IDC_SPIN_AT_MINUTE              2296
#define IDC_WORLD_LIST                  2297
#define IDC_SPIN_AT_SECOND              2298
#define IDC_AUTO_CONNECT                2299
#define IDC_SPIN_EVERY_HOUR             2300
#define IDC_RECONNECT                   2301
#define IDC_SPIN_EVERY_MINUTE           2302
#define IDC_OPEN_WORLDS_MAXIMISED       2303
#define IDC_SPIN_EVERY_SECOND           2304
#define IDC_SPIN_OFFSET_HOUR            2305
#define IDC_SPIN_OFFSET_MINUTE          2306
#define IDC_TOP_MARGIN                  2307
#define IDC_SPIN_OFFSET_SECOND          2308
#define IDC_LEFT_MARGIN                 2309
#define IDC_FONT                        2310
#define IDC_DEFAULT_DIRECTORY           2311
#define IDC_LINES_PER_PAGE              2312
#define IDC_DEFAULT_DIRECTORY_NAME      2313
#define IDC_AUTO_LOG                    2314
#define IDC_AUTO_APPEND                 2315
#define IDC_TIMER_INTERVAL              2316
#define IDC_EXPRESSION                  2317
#define IDC_LANGUAGE                    2318
#define IDC_LOW_PRIORITY                2319
#define IDC_NORMAL_PRIORITY             2320
#define IDC_HIGH_PRIORITY               2321
#define IDC_SCRIPT_FILENAME             2322
#define IDC_BROWSE                      2323
#define IDC_ON_WORLD_OPEN               2324
#define IDC_ON_WORLD_CONNECT            2325
#define IDC_ON_MXP_SHUTDOWN             2326
#define IDC_ON_WORLD_CLOSE              2327
#define IDC_ON_MXP_OPENING_TAG          2328
#define IDC_ON_WORLD_SAVE               2328
#define IDC_ON_WORLD_DISCONNECT         2329
#define IDC_ON_MXP_CLOSING_TAG          2330
#define IDC_ENABLE                      2331
#define IDC_ON_MXP_SET_VARIABLE         2332
#define IDC_DISABLE                     2332
#define IDC_CLEAR_VARIABLES             2333
#define IDC_ON_MXP_ERROR                2334
#define IDC_ON_WORLD_GET_FOCUS          2335
#define IDC_ADD_VARIABLE                2336
#define IDC_ON_WORLD_LOSE_FOCUS         2337
#define IDC_CHANGE_VARIABLE             2338
#define IDC_DELETE_VARIABLE             2339
#define IDC_VARIABLES_LIST              2340
#define IDC_VARIABLE_CONTENTS           2341
#define IDC_VARIABLE_NAME               2342
#define IDC_FIND_TEXT                   2343
#define IDC_FIND_UP                     2344
#define IDC_FIND_DOWN                   2345
#define IDC_MATCH_CASE                  2346
#define IDC_FIND                        2347
#define IDC_FIND_NEXT                   2348
#define IDC_EXCLUDE_NON_ALPHA           2349
#define IDC_EXCLUDE_MACROS              2350
#define IDC_OVERRIDE_PREFIX             2351
#define IDC_AUTO_SAY_STRING             2352
#define IDC_ENABLE_AUTOSAY              2353
#define IDC_PRINT_BOLD0                 2354
#define IDC_PRINT_ITALIC0               2355
#define IDC_PRINT_UNDERLINE0            2356
#define IDC_PRINT_BOLD1                 2357
#define IDC_APPEND_TO_LOG_FILE          2358
#define IDC_PRINT_ITALIC1               2359
#define IDC_OPEN_ACTIVITY               2360
#define IDC_PRINT_UNDERLINE1            2361
#define IDC_NEW_STARTUP_WORLD           2362
#define IDC_PRINT_BOLD2                 2363
#define IDC_REMOVE_STARTUP_WORLD        2364
#define IDC_PRINT_ITALIC2               2365
#define IDC_WORLD_COUNT                 2366
#define IDC_PRINT_UNDERLINE2            2367
#define IDC_ACTIVITY_INTERVAL           2368
#define IDC_PRINT_BOLD3                 2369
#define IDC_UPDATE_ACTIVITY             2370
#define IDC_PRINT_ITALIC3               2371
#define IDC_PERIODICALLY                2372
#define IDC_PRINT_UNDERLINE3            2373
#define IDC_BOTH                        2374
#define IDC_PRINT_BOLD4                 2375
#define IDC_PERIOD_SPIN                 2376
#define IDC_PRINT_ITALIC4               2377
#define IDC_PRINT_UNDERLINE4            2378
#define IDC_PRINT_BOLD5                 2379
#define IDC_PRINT_ITALIC5               2380
#define IDC_SPIN_WRAP_COLUMN            2381
#define IDC_SPIN_MATCH_WIDTH            2382
#define IDC_PRINT_UNDERLINE5            2383
#define IDC_SPIN_HISTORY_LINES          2384
#define IDC_SPIN_OFFSET                 2385
#define IDC_PRINT_BOLD6                 2386
#define IDC_SPIN_LINE_SPACING           2386
#define IDC_ANSI_COLOURS                2387
#define IDC_PRINT_ITALIC6               2388
#define IDC_SCRIPT_NAME                 2389
#define IDC_PRINT_UNDERLINE6            2390
#define IDC_GROUP                       2390
#define IDC_PRINT_BOLD7                 2391
#define IDC_SCRIPT_PREFIX               2392
#define IDC_PRINT_ITALIC7               2393
#define IDC_SCRIPT_TEXT_SWATCH          2394
#define IDC_PRINT_UNDERLINE7            2395
#define IDC_SCRIPT_TEXT_SWATCH2         2396
#define IDC_ERROR_LIST                  2397
#define IDC_INVOCATIONS                 2398
#define IDC_ONE_SHOT_TIMER              2399
#define IDC_PRINT_BOLD8                 2400
#define IDC_PRINT_ITALIC8               2401
#define IDC_FORM_TYPE                   2402
#define IDC_PRINT_UNDERLINE8            2403
#define IDC_PRINT                       2404
#define IDC_PRINT_BOLD9                 2405
#define IDC_SAVE                        2406
#define IDC_PRINT_ITALIC9               2407
#define IDC_VERSION_LABEL               2408
#define IDC_PRINT_UNDERLINE9            2409
#define IDC_REGISTERED_USER             2410
#define IDC_PRINT_BOLD10                2411
#define IDC_PRINT_ITALIC10              2412
#define IDC_SAVE_AUTOMATICALLY          2413
#define IDC_PRINT_UNDERLINE10           2414
#define IDC_PRINT_BOLD11                2415
#define IDC_CONFIRM_REPLACE_TYPING      2416
#define IDC_PRINT_ITALIC11              2417
#define IDC_PRINT_UNDERLINE11           2418
#define IDC_PRINT_BOLD12                2419
#define IDC_PRINT_ITALIC12              2420
#define IDC_PRINT_UNDERLINE12           2421
#define IDC_PRINT_BOLD13                2422
#define IDC_PRINT_ITALIC13              2423
#define IDC_PRINT_UNDERLINE13           2424
#define IDC_PRINT_BOLD14                2425
#define IDC_PRINT_ITALIC14              2426
#define IDC_PRINT_UNDERLINE14           2427
#define IDC_PRINT_BOLD15                2428
#define IDC_PRINT_ITALIC15              2429
#define IDC_PRINT_UNDERLINE15           2430
#define IDC_SPIN_TOP_MARGIN             2431
#define IDC_SPIN_LEFT_MARGIN            2432
#define IDC_SPIN_LINES_PER_PAGE         2433
#define IDC_SPIN_TIMER                  2434
#define IDC_WRITE_WORLD_NAME            2435
#define IDC_LOGO                        2436
#define IDC_LINE_INFORMATION            2437
#define IDC_START_PAUSED                2438
#define IDC_LOG_NOTES                   2439
#define IDC_HISTORY_ITEM                2440
#define IDC_LOG_HTML                    2441
#define IDC_ESCAPE_DELETES_TYPING       2442
#define IDC_LOG_COLOUR                  2443
#define IDC_ARROW_KEYS_TRAVERSE_HISTORY 2444
#define IDC_CHOOSE_EDITOR               2445
#define IDC_SCRIPT_EDITOR               2446
#define IDC_LOG_FILE_PREAMBLE           2447
#define IDC_CONFIRM_ON_PASTE            2448
#define IDC_LOG_FILE_POSTAMBLE          2449
#define IDC_SHOW_BOLD                   2450
#define IDC_WEB_ADDRESS                 2451
#define IDC_SHOW_ITALIC                 2452
#define IDC_RECALL_PARTIAL              2453
#define IDC_SHOW_UNDERLINE              2454
#define IDC_CONFIG_INPUT                2455
#define IDC_CONFIG_TRIGGERS             2456
#define IDC_CONFIG_PASTE                2457
#define IDC_CONFIG_SCRIPTING            2458
#define IDC_MUD_NAME                    2459
#define IDC_MUD_ADDRESS                 2460
#define IDC_MUD_PORT                    2461
#define IDC_MUD_TYPE2                   2462
#define IDC_MUD_COMMENTS                2463
#define IDC_MESSAGE                     2464
#define IDC_MESSAGE1                    2465
#define IDC_MESSAGE2                    2466
#define IDC_CHANGES_ADDRESS             2467
#define IDC_MUD_LISTS                   2468
#define IDC_REGCODE                     2469
#define IDC_EDIT1                       2470
#define IDC_VERSION                     2471
#define IDC_AUTHOR                      2471
#define IDC_SPEED_WALK_FILLER           2472
#define IDC_PURPOSE                     2472
#define IDC_WHAT                        2472
#define IDC_HIGH_VERSION                2473
#define IDC_DATE_WRITTEN                2473
#define IDC_CURRENT_LINE                2473
#define IDC_LINE_COUNT                  2474
#define IDC_VERSION2                    2474
#define IDC_FUNC_NAME                   2474
#define IDC_SPEED_WALK_DELAY            2475
#define IDC_ID                          2475
#define IDC_FUNCTION                    2475
#define IDC_WORD_DELIMITERS             2476
#define IDC_REQUIRES                    2476
#define IDC_NUPS                        2476
#define IDC_STATUS                      2477
#define IDC_SEQUENCE                    2478
#define IDC_MAX_SOCKETS                 2479
#define IDC_LOG_FILE                    2480
#define IDC_HOST_NAME                   2481
#define IDC_SEND_TEXT                   2482
#define IDC_ADDRESSES                   2483
#define IDC_CUSTOM_NAME1                2484
#define IDC_DEFAULT_COLOURS             2485
#define IDC_LETTER                      2486
#define IDC_ERROR_NUMBER                2487
#define IDC_PIXEL_OFFSET                2488
#define IDC_WORD_DELIMITERS2            2489
#define IDC_CUSTOM_NAME2                2490
#define IDC_DEFAULT_TRIGGERS            2491
#define IDC_EVENT                       2492
#define IDC_AUTOFREEZE                  2493
#define IDC_CUSTOM_NAME3                2494
#define IDC_UNPAUSEONSEND               2495
#define IDC_DEFAULT_ALIASES             2496
#define IDC_BACK_COLOUR                 2497
#define IDC_DESCRIPTION                 2498
#define IDC_BACK_COLOUR_RGB             2498
#define IDC_AUTO_REPEAT                 2499
#define IDC_CUSTOM_NAME4                2500
#define IDC_DEFAULT_MACROS              2501
#define IDC_CUSTOM_COLOUR               2502
#define IDC_CALLED_BY                   2503
#define IDC_DISABLE_COMPRESSION         2504
#define IDC_CUSTOM_NAME5                2505
#define IDC_DEFAULT_TIMERS              2506
#define IDC_CHECK1                      2507
#define IDC_ENABLE_SPAM_PREVENTION      2507
#define IDC_ECHO_ALIAS                  2507
#define IDC_ACCEPT_CALLS                2507
#define IDC_INCOMING                    2507
#define IDC_ZCHAT                       2507
#define IDC_RE_EVALUATE_AUTO_SAY        2507
#define IDC_AUTO_COPY_HTML              2507
#define IDC_CONTROL_KEY                 2507
#define IDC_REMOVE_CHECK                2507
#define IDC_REMOVE_ITEMS                2507
#define IDC_MULTI_LINE                  2507
#define IDC_WARN_IF_INACTIVE            2507
#define IDC_WHOLE_WORD                  2507
#define IDC_EACH_LINE                   2507
#define IDC_ENABLE_PACKAGE_LIBRARY      2507
#define IDC_USE_OUTPUT_WINDOW           2507
#define IDC_TAB_COMPLETION_SPACE        2507
#define IDC_UNICODE_HEX                 2507
#define IDC_WORD_WRAP                   2508
#define IDC_CAN_SNOOP                   2508
#define IDC_USE_NOTEPAD                 2509
#define IDC_CAN_SEND_FILES              2509
#define IDC_SMOOTHER_SCROLLING          2510
#define IDC_PRIVATE                     2510
#define IDC_IGNORE_COLOURS              2511
#define IDC_IGNORE                      2511
#define IDC_REMOVE_REVERSES             2512
#define IDC_CAN_SEND_COMMANDS           2512
#define IDC_SEND_TO_MUD                 2513
#define IDC_ALTERNATIVE_INVERSE         2514
#define IDC_ARROW_KEYS_RECALL_PARTIAL_COMMAND 2515
#define IDC_CONFIRM_BEFORE_CLOSING_MXP_DEBUG 2516
#define IDC_USE_CUSTOM_LINK             2517
#define IDC_USE_CUSTOM_COLOUR_16        2518
#define IDC_ALIAS_MENU                  2519
#define IDC_RAW_LOG                     2520
#define IDC_TEMPORARY                   2521
#define IDC_GENERAL                     2522
#define IDC_LOWER_CASE_TAB_COMPLETION   2523
#define IDC_SMOOTH_SCROLLING            2524
#define IDC_SAVE_HYPERLINK_CLICKS       2525
#define IDC_REPEAT                      2526
#define IDC_AUTO_EXPAND                 2527
#define IDC_ECHO                        2528
#define IDC_ECHO_LINES                  2529
#define IDC_CUSTOM_NAME6                2530
#define IDC_OUTPUT                      2531
#define IDC_DOUBLE_CLICK_INSERTS        2532
#define IDC_CUSTOM_NAME7                2533
#define IDC_SEND_TO_COMMAND             2534
#define IDC_DOUBLE_CLICK_SENDS          2535
#define IDC_CUSTOM_NAME8                2536
#define IDC_EXPAND_VARIABLES            2537
#define IDC_CUSTOM_NAME9                2538
#define IDC_LINE_DELAY                  2539
#define IDC_CUSTOM_NAME10               2540
#define IDC_LINE_DELAY_PER_LINES        2541
#define IDC_COMMENTED_SOFTCODE          2542
#define IDC_CUSTOM_NAME11               2543
#define IDC_CONFIRM_ON_SEND             2544
#define IDC_CUSTOM_NAME12               2545
#define IDC_FLASH_ICON                  2546
#define IDC_CUSTOM_NAME13               2547
#define IDC_CLICK_MESSAGE               2548
#define IDC_CUSTOM_NAME14               2549
#define IDC_TRANSLATE_GERMAN            2550
#define IDC_CUSTOM_NAME15               2551
#define IDC_BUG_REPORT                  2552
#define IDC_CUSTOM_NAME16               2553
#define IDC_WORD_LIST                   2554
#define IDC_CHANGE_FROM                 2555
#define IDC_CHANGE_TO                   2556
#define IDC_MATCHES                     2557
#define IDC_REGEXP                      2558
#define IDC_ARROWS_WRAP                 2559
#define IDC_SPEED_WALK                  2560
#define IDC_NOTIFY_DISCONNECT           2561
#define IDC_QUEUE                       2562
#define IDC_CONFIRM_LOG_FILE_CLOSE      2563
#define IDC_TREE1                       2564
#define IDC_SPELL_CHECK_ON_SEND         2565
#define IDC_ENABLE_SPELL_CHECK          2566
#define IDC_SWAP                        2567
#define IDC_BOLD                        2568
#define IDC_ITALIC                      2569
#define IDC_UNDERLINE                   2570
#define IDC_SEND_TO_GROUP               2571
#define IDC_SOUND_IF_INACTIVE           2572
#define IDC_LINE_PREAMBLE_OUTPUT        2573
#define IDC_LINE_PREAMBLE_INPUT         2574
#define IDC_SELECT_OUTPUT_FONT          2575
#define IDC_LINE_POSTAMBLE_OUTPUT       2576
#define IDC_LINE_PREAMBLE_NOTES         2577
#define IDC_DEFAULT_OUTPUT_FONT         2578
#define IDC_LINE_POSTAMBLE_INPUT        2579
#define IDC_SELECT_INPUT_FONT           2580
#define IDC_LINE_POSTAMBLE_NOTES        2581
#define IDC_USE_DEFAULT_COLOURS         2582
#define IDC_DEFAULT_INPUT_FONT          2583
#define IDC_USE_DEFAULT_TRIGGERS        2584
#define IDC_AUSTRALIAN                  2585
#define IDC_USE_DEFAULT_ALIASES         2586
#define IDC_USE_DEFAULT_MACROS          2587
#define IDC_USE_DEFAULT_TIMERS          2588
#define IDC_USE_DEFAULT_INPUT_FONT      2589
#define IDC_USE_DEFAULT_OUTPUT_FONT     2590
#define IDC_COLOUR_GRADIENT             2591
#define IDC_TIME_TAKEN                  2592
#define IDC_CREDITS                     2593
#define IDC_TIME_TAKEN_COMPRESSING      2594
#define IDC_CREDITS_LIST                2595
#define IDC_TEXT                        2596
#define IDC_GENERATED_NAME              2597
#define IDC_MATCH_BOLD                  2598
#define IDC_MATCH_ITALIC                2599
#define IDC_MATCH_INVERSE               2600
#define IDC_MODIFIED                    2601
#define IDC_INVERSE                     2602
#define IDC_BLEED_BACKGROUND            2603
#define IDC_INPUT_STYLE                 2604
#define IDC_OUTPUT_STYLE                2605
#define IDC_FIXED_FONT                  2606
#define IDC_LOAD_VARIABLES              2607
#define IDC_SAVE_VARIABLES              2608
#define IDC_SAVE_DELETED                2609
#define IDC_TRANSLATE_BACKSLASH         2610
#define IDC_REGISTER_NOW                2611
#define IDC_TRANSLATE_BACKSLASH2        2612
#define IDC_REGISTER                    2613
#define IDC_DO                          2614
#define IDC_CONFIG_NAME                 2615
#define IDC_EXPORT_ALIASES              2616
#define IDC_ADJUST_WIDTH                2617
#define IDC_TAB_COMPLETION_DEFAULTS     2618
#define IDC_SWATCH_CUSTOM10             2619
#define IDC_SELECT_ALL                  2620
#define IDC_MOVE_UP                     2621
#define IDC_BROWSE_COLOURS              2622
#define IDC_COPY                        2623
#define IDC_BUTTON2                     2624
#define IDC_SUBSITUTION_HELP            2624
#define IDC_INVERT                      2624
#define IDC_LUA_FUNCTIONS               2624
#define IDC_EDIT_FUNCTION               2624
#define IDC_COMPLETE_WORD               2624
#define IDC_EDIT_COMMAND                2624
#define IDC_CLEAR_CACHED                2624
#define IDC_INSERT_UNICODE              2624
#define IDC_SPECIAL_MOVE                2625
#define IDC_RANDOM                      2625
#define IDC_GOTO_LINE                   2625
#define IDC_CONVERT_TO_REGEXP           2626
#define IDC_RELOAD                      2627
#define IDC_PLUGINS_DIRECTORY           2628
#define IDC_EDIT_SCRIPT                 2629
#define IDC_CONFIG_APPEARANCE           2630
#define IDC_SELECT1                     2631
#define IDC_SPELL_CHECK_OPTIONS         2632
#define IDC_SWATCH_CUSTOM11             2633
#define IDC_SPELL_CHECK_DICTIONARIES    2634
#define IDC_SELECT_NONE                 2635
#define IDC_BROWSE_TRIGGERS             2636
#define IDC_SEND_TO_WORLD               2637
#define IDC_PROGRESS_BAR                2638
#define IDC_SWATCH_CUSTOM12             2639
#define IDC_MOVE_DOWN                   2640
#define IDC_BROWSE_ALIASES              2641
#define IDC_MASTERCARD                  2642
#define IDC_SELECT2                     2643
#define IDC_SWATCH_CUSTOM13             2644
#define IDC_BROWSE_MACROS               2645
#define IDC_VISA                        2646
#define IDC_REGISTRATION_CODE           2647
#define IDC_SELECT3                     2648
#define IDC_SWATCH_CUSTOM14             2649
#define IDC_BROWSE_TIMERS               2650
#define IDC_CHEQUE                      2651
#define IDC_PHONE_NUMBER                2652
#define IDC_SELECT4                     2653
#define IDC_SWATCH_CUSTOM15             2654
#define IDC_CASH                        2655
#define IDC_FAX_NUMBER                  2656
#define IDC_SELECT5                     2657
#define IDC_SWATCH_CUSTOM16             2658
#define IDC_POSTAL_ORDER                2659
#define IDC_CC_LABEL                    2660
#define IDC_SELECT6                     2661
#define IDC_CONFIRM_BEFORE_CLOSING_WORLD 2662
#define IDC_CONFIRM_BEFORE_CLOSING_MUSHCLIENT 2663
#define IDC_SELECT_NOTEPAD_FONT         2664
#define IDC_CONFIRM_BEFORE_SAVING_VARIABLES 2665
#define IDC_DEFAULT_NOTEPAD_FONT        2666
#define IDC_NOTEPAD_STYLE               2667
#define IDC_NOTEPAD_LIST                2668
#define IDC_BRACES_NEST                 2669
#define IDC_BACKSLASH_ESCAPES           2670
#define IDC_PERCENT_ESCAPES             2671
#define IDC_SINGLE_QUOTES               2672
#define IDC_DOUBLE_QUOTES               2673
#define IDC_ESCAPE_SINGLE_QUOTES        2674
#define IDC_ESCAPE_DOUBLE_QUOTES        2675
#define IDC_ALL_TYPING_TO_COMMAND       2676
#define IDC_FORWARDS                    2677
#define IDC_BACKWARDS                   2678
#define IDC_MAPPING_FAILURE             2679
#define IDC_ACTION                      2680
#define IDC_MAKE_ALIAS                  2681
#define IDC_MAKE_REVERSE_ALIAS          2682
#define IDC_TAKE_REVERSE                2683
#define IDC_EXECUTION_TIME              2684
#define IDC_ORDERS_WEB_PAGE             2685
#define IDC_LAYOUT                      2686
#define IDC_FILENAME                    2687
#define IDC_MXP_OPTION                  2688
#define IDC_MXP_DEBUG_LEVEL             2689
#define IDC_MXP_ACTIVE                  2690
#define IDC_CTRL_Z_END_WINDOW           2691
#define IDC_CTRL_P_PREVIOUS_COMMAND     2692
#define IDC_CTRL_N_PREVIOUS_COMMAND     2693
#define IDC_ON_MXP_STARTUP              2694
#define IDC_COLOUR_NAME                 2695
#define IDC_MXP_NAME                    2696
#define IDC_ECHO_HYPERLINK_CLICKS       2697
#define IDC_VB_NAME                     2698
#define IDC_MXP_BUILTIN_ELEMENTS        2699
#define IDC_JSCRIPT_NAME                2700
#define IDC_MXP_BUILTIN_ENTITIES        2701
#define IDC_AUTO_WRAP_WINDOW            2702
#define IDC_MXP_MUD_ELEMENTS            2703
#define IDC_COLOURLIST                  2704
#define IDC_MXP_MUD_ENTITIES            2705
#define IDC_COLOUR_SORT                 2706
#define IDC_MXP_ERRORS                  2707
#define IDC_MXP_TAGS_RECEIVED           2708
#define IDC_MXP_ENTITIES_RECEIVED       2709
#define IDC_MXP_UNCLOSED_TAGS           2710
#define IDC_COMPRESSED_IN               2711
#define IDC_COMPRESSED_OUT              2712
#define IDC_CONNECT_OPTION              2713
#define IDC_MXP_REFERENCE_COUNT         2714
#define IDC_PUEBLO                      2715
#define IDC_MXP_ACTIONS_CACHED          2716
#define IDC_HYPERLINK_SWATCH            2717
#define IDC_NO_ECHO_OFF                 2718
#define IDC_CHAT_BACK_SWATCH            2718
#define IDC_MUD_CAN_CHANGE_LINK_COLOUR  2719
#define IDC_UNDERLINE_HYPERLINKS        2720
#define IDC_MUD_CAN_REMOVE_UNDERLINE    2721
#define IDC_TERMINAL_TYPE               2722
#define IDC_SHOW_CONNECT_DISCONNECT     2723
#define IDC_IGNORE_COLOUR_CHANGES       2724
#define IDC_ACTIVITY_BUTTONS_STYLE      2725
#define IDC_REGEXP_MATCH_EMPTY          2726
#define IDC_EDIT_SEND                   2727
#define IDC_TEMPORARY_ALIAS             2728
#define IDC_EDIT_POSTAMBLE              2728
#define IDC_SPEEDWALK                   2729
#define IDC_NOTE                        2730
#define IDC_ACTIVE_WHEN_CLOSED          2731
#define IDC_NOTIFY_IF_CANNOT_CONNECT    2732
#define IDC_PLUGINS_LIST                2733
#define IDC_ADD_PLUGIN                  2734
#define IDC_DELETE_PLUGIN               2735
#define IDC_PLUGINS_DIRECTORY_NAME      2736
#define IDC_NAME                        2737
#define IDC_TRIGGER_LIST                2739
#define IDC_ALIAS_LIST                  2740
#define IDC_TIMER_LIST                  2741
#define IDC_VARIABLE_LIST               2742
#define IDC_HELP_ALIAS                  2743
#define IDC_SCRIPT                      2744
#define IDC_COMMENTS                    2745
#define IDC_EDIT_CONTENTS               2746
#define IDC_EDIT_PREAMBLE               2747
#define IDC_COMMENT                     2748
#define IDC_INFOTEXT                    2751
#define IDC_QUOTE_STRING                2752
#define IDC_MUD_CAN_CHANGE_OPTIONS      2753
#define IDC_RETAIN_STATE                2754
#define IDC_INCLUDE_CONSTANTS           2755
#define IDC_GENERATE_HELP               2756
#define IDC_LOWERCASE_WILDCARD          2757
#define IDC_COPY_SELECTION_TO_CLIPBOARD 2758
#define IDC_SEND_AFK_RESPONSE           2759
#define IDC_SHOW_GRID_LINES             2760
#define IDC_SPAM_LINE_COUNT             2761
#define IDC_SPAM_FILLER                 2762
#define IDC_VARIABLE                    2763
#define IDC_PROXY_TYPE                  2764
#define IDC_PROXY_PORT                  2765
#define IDC_PROXY_SERVER_NAME           2766
#define IDC_CHAT_NAME                   2767
#define IDC_CHAT_PORT                   2768
#define IDC_VALIDATE_CALLS              2769
#define IDC_CHAT_TEXT_SWATCH            2771
#define IDC_CHAT_PREFIX                 2772
#define IDC_MAX_MESSAGE_LINES           2773
#define IDC_MAX_MESSAGE_BYTES           2774
#define IDC_AUTO_ACCEPT_FILES           2775
#define IDC_CHAT_SAVE_DIRECTORY         2776
#define IDC_AUTO_ACCEPT_SNOOP           2777
#define IDC_CHAT_SESSIONS               2778
#define IDC_PORT                        2779
#define IDC_CHAT_ID                     2780
#define IDC_HANGUP                      2781
#define IDC_CLIENT                      2781
#define IDC_PEEK                        2782
#define IDC_REQUEST                     2783
#define IDC_PING                        2784
#define IDC_SENDFILE                    2785
#define IDC_SNOOP                       2786
#define IDC_CHAT                        2787
#define IDC_EMOTE                       2788
#define IDC_CHAT_ALL                    2789
#define IDC_EMOTE_ALL                   2790
#define IDC_EMOTE_TEXT                  2791
#define IDC_SAY_TEXT                    2792
#define IDC_CHATNAME                    2793
#define IDC_LINE_SPACING                2795
#define IDC_OMIT_FROM_COMMAND_HISTORY   2796
#define IDC_ACTUAL_IP                   2797
#define IDC_CALL_IP                     2798
#define IDC_LOGON_NAME                  2800
#define IDC_LOGON_PASSWORD              2801
#define IDC_SELECTED_WORLD              2801
#define IDC_UTF_8                       2802
#define IDC_INCLUDED                    2803
#define IDC_F1_MACRO                    2804
#define IDC_MINIMISE_TO                 2805
#define IDC_MUSHCLIENT_ICON             2806
#define IDC_CD_ICON                     2807
#define IDC_SPANNER_ICON                2808
#define IDC_CLOCK_ICON                  2809
#define IDC_WORLD_ICON                  2810
#define IDC_GRAPH_ICON                  2811
#define IDC_HANDS_ICON                  2812
#define IDC_MAIL_ICON                   2813
#define IDC_NETWORK_ICON                2814
#define IDC_BANANA_ICON                 2815
#define IDC_CUSTOM_ICON                 2816
#define IDC_ICON_FILE_NAME              2817
#define IDC_SELECTED_PLUGIN             2818
#define IDC_PLUGIN_LIST                 2819
#define IDC_NEW_PLUGIN                  2820
#define IDC_REMOVE_PLUGIN               2821
#define IDC_PLUGIN_COUNT                2822
#define IDC_CARRIAGE_RETURN_CLEARS_LINE 2823
#define IDC_LINES_TO_MATCH              2824
#define IDC_REGEXP_TEXT                 2825
#define IDC_ERROR_MESSAGE               2826
#define IDC_COLUMN                      2827
#define IDC_INSERT_SPECIAL              2829
#define IDC_VARIABLE_LABEL              2831
#define IDC_LUA_SCRIPT                  2832
#define IDC_TABS                        2833
#define IDC_RGB_TEXT_SWATCH             2834
#define IDC_HIGHLIGHT_TEXT              2835
#define IDC_TRIGGER_SWATCH_TEXT         2837
#define IDC_TRIGGER_SWATCH_BGND         2838
#define IDC_RED_SLIDER                  2841
#define IDC_GREEN_SLIDER                2842
#define IDC_BLUE_SLIDER                 2843
#define IDC_FLAT_TOOLBARS               2843
#define IDC_LUA_NAME                    2845
#define IDC_TRIGGER_TEXT                2847
#define IDC_IS_ACTIVE                   2848
#define IDC_CONVERT_GA_TO_NEWLINE       2849
#define IDC_INPUT_BOX_MESSAGE           2850
#define IDC_INPUT_BOX_REPLY             2851
#define IDC_CHOOSE_MSG                  2852
#define IDC_CHOOSE_COMBO                2855
#define IDC_CHOOSE_LIST                 2856
#define IDC_FUNCTIONS_LIST              2857
#define IDC_FILTER                      2858
#define IDC_FIND_PATTERN                2859
#define IDC_REPLACEMENT                 2860
#define IDC_ESCAPE_SEQUENCES            2861
#define IDC_EDIT_FIND                   2863
#define IDC_SELECTION_SIZE              2864
#define IDC_COLOUR_CHANGE_TYPE          2865
#define IDC_NOTIFY_TO_OUTPUT            2866
#define IDC_HOTKEY_VALUE                2868
#define IDC_TEXT_NAME                   2869
#define IDC_ERRORS_AS_NOTES             2870
#define IDC_SOURCE                      2872
#define IDC_SHOW_LOCALS                 2873
#define IDC_COMMAND                     2874
#define ID_DO_COMMAND                   2875
#define IDC_TRACEBACK                   2876
#define IDC_ABORT                       2877
#define IDC_TAB_COMPLETION_LINES        2878
#define ID_IGNORE                       2880
#define ID_IGNORE_ALL                   2881
#define ID_ADD                          2882
#define ID_CHANGE                       2883
#define ID_CHANGE_ALL                   2884
#define ID_MISSPELT_WORD                2887
#define ID_SUGGESTIONS                  2888
#define IDC_RAISED_BY_LABEL             2889
#define IDC_COUNT                       2890
#define IDC_UNICODE_CHARACTER           2891
#define IDC_REGEXP_ERROR                2892
#define IDC_ONE_SHOT                    2893
#define IDC_LOCALE                      2895
#define IDC_DISABLE_KEYBOARD_MENU_ACTIVATION 2896
#define IDS_CHANGEADDRESS               32100
#define IDS_DISCONNECT                  32101
#define IDS_CREATEFAILED                32102
#define IDS_RETRYCONNECT                32103
#define IDS_CONNECT                     32104
#define IDS_SERVERRESET                 32105
#define IDS_CONNECTIONCLOSED            32106
#define ID_TEST_END                     32107
#define ID_EDIT_SELECTALL               32108
#define ID_KEYS_NEXTCOMMAND             32109
#define ID_KEYS_PREVCOMMAND             32110
#define ID_TEST_PAGEUP                  32111
#define ID_TEST_PAGEDOWN                32112
#define ID_EDIT_GOTO                    32113
#define ID_TEST_START                   32114
#define ID_TEST_LINEUP                  32115
#define ID_TEST_LINEDOWN                32116
#define ID_FILE_LOGSESSION              32117
#define ID_GAME_WRAPLINES               32118
#define ID_STATUSLINE_MUSHNAME          32119
#define ID_STATUSLINE_TIME              32120
#define ID_STATUSLINE_LINES             32121
#define ID_CONVERT_UNIXTODOS            32122
#define ID_CONVERT_DOSTOUNIX            32123
#define ID_STATUSLINE_LOG               32124
#define ID_CONVERT_MACTODOS             32125
#define ID_GAME_NORTH                   32126
#define ID_CONVERT_DOSTOMAC             32127
#define ID_GAME_SOUTH                   32128
#define ID_CONVERT_REMOVEENDOFLINES     32129
#define ID_GAME_EAST                    32130
#define ID_CONVERT_QUOTELINES           32131
#define ID_GAME_WEST                    32132
#define ID_WINDOW_CLOSEALL              32133
#define ID_GAME_UP                      32134
#define ID_GAME_DOWN                    32136
#define ID_EDIT_INSERTDATETIME          32137
#define ID_GAME_EXAMINE                 32138
#define ID_EDIT_WORDCOUNT               32139
#define ID_GAME_LOOK                    32140
#define ID_KEYS_ACTIVATECOMMANDVIEW     32142
#define ID_GAME_SAY                     32143
#define ID_CONVERT_UPPERCASE            32144
#define ID_GAME_WHISPER                 32145
#define ID_CONVERT_LOWERCASE            32146
#define ID_GAME_PAGESOMEONE             32147
#define ID_CONVERT_REMOVEEXTRABLANKS    32148
#define ID_GAME_POSE                    32149
#define ID_GAME_EDITGAMEDETAILS         32150
#define ID_GAME_COMMANDHISTORY          32152
#define ID_GAME_WHO                     32154
#define ID_GAME_DOING                   32156
#define ID_GAME_PREFERENCES             32158
#define ID_GAME_TAKE                    32160
#define ID_GAME_DROP                    32162
#define ID_DISPLAY_ACTIVATECOMMANDAREA  32164
#define ID_VIEW_MAXIMIZE                32165
#define ID_DISPLAY_PREVIOUSCOMMAND      32166
#define ID_DISPLAY_NEXTCOMMAND          32167
#define ID_MACRO_F2                     32168
#define ID_MACRO_F3                     32169
#define ID_MACRO_F4                     32170
#define ID_MACRO_F5                     32171
#define ID_MACRO_F6                     32172
#define ID_MACRO_F7                     32173
#define ID_MACRO_F8                     32174
#define ID_MACRO_F9                     32175
#define ID_MACRO_F10                    32176
#define ID_MACRO_F11                    32177
#define ID_MACRO_F12                    32178
#define ID_MACRO_CTRL_F2                32179
#define ID_MACRO_CTRL_F3                32180
#define ID_MACRO_CTRL_F4                32181
#define ID_MACRO_CTRL_F5                32182
#define ID_MACRO_CTRL_F6                32183
#define ID_MACRO_CTRL_F7                32184
#define ID_MACRO_CTRL_F8                32185
#define ID_MACRO_CTRL_F9                32186
#define ID_MACRO_CTRL_F10               32187
#define ID_MACRO_CTRL_F11               32188
#define ID_MACRO_CTRL_F12               32189
#define ID_MACRO_SHIFT_F2               32190
#define ID_MACRO_SHIFT_F3               32191
#define ID_MACRO_SHIFT_F4               32192
#define ID_MACRO_SHIFT_F5               32193
#define ID_MACRO_SHIFT_F6               32194
#define ID_MACRO_SHIFT_F7               32195
#define ID_MACRO_SHIFT_F8               32196
#define ID_MACRO_SHIFT_F9               32197
#define ID_MACRO_SHIFT_F10              32198
#define ID_MACRO_SHIFT_F11              32199
#define ID_MACRO_SHIFT_F12              32200
#define ID_DISPLAY_FREEZEOUTPUT         32201
#define ID_STATUSLINE_FREEZE            32202
#define ID_DISPLAY_ACTIVITYLIST         32203
#define ID_WORLDS_WORLD1                32204
#define ID_WORLDS_WORLD2                32205
#define ID_WORLDS_WORLD3                32206
#define ID_WORLDS_WORLD4                32207
#define ID_WORLDS_WORLD5                32208
#define ID_WORLDS_WORLD6                32209
#define ID_WORLDS_WORLD7                32210
#define ID_WORLDS_WORLD8                32211
#define ID_WORLDS_WORLD9                32212
#define ID_WORLDS_WORLD0                32213
#define ID_GAME_TESTCOMMAND             32214
#define ID_GAME_TESTTRIGGER             32215
#define ID_GAME_PASTEFILE               32216
#define ID_ACTIONS_QUIT                 32217
#define ID_ACTIONS_LOGOUT               32218
#define ID_KEYPAD_0                     32219
#define ID_KEYPAD_1                     32220
#define ID_KEYPAD_2                     32221
#define ID_KEYPAD_3                     32222
#define ID_KEYPAD_4                     32223
#define ID_KEYPAD_5                     32224
#define ID_KEYPAD_6                     32225
#define ID_KEYPAD_7                     32226
#define ID_KEYPAD_8                     32227
#define ID_KEYPAD_9                     32228
#define ID_KEYPAD_DOT                   32229
#define ID_KEYPAD_SLASH                 32230
#define ID_KEYPAD_STAR                  32231
#define ID_KEYPAD_DASH                  32232
#define ID_KEYPAD_PLUS                  32233
#define ID_GAME_MINIMISEPROGRAM         32234
#define ID_WINDOW_MINIMIZE              32235
#define ID_VIEW_TESTBUG                 32236
#define ID_HELP_TIPOFTHEDAY             32237
#define ID_HELP_REGISTERMUSHCLIENT      32238
#define ID_CONNECTION_CONNECT           32239
#define ID_CONNECTION_DISCONNECT        32240
#define ID_CONNECTION_AUTOCONNECT       32241
#define ID_POPUP_SWITCHTOWORLD          32242
#define ID_POPUP_CONFIGUREWORLD         32243
#define ID_EDIT_PASTETOMUSH             32244
#define ID_VIEW_GAMETOOLBAR             32245
#define ID_FILE_PREFERENCES             32246
#define ID_GAME_IMMEDIATE               32247
#define ID_DISPLAY_FIND                 32248
#define ID_DISPLAY_FINDAGAIN            32249
#define ID_FILE_PRINT_WORLD             32250
#define ID_HELP_CONTENTS                32251
#define ID_GAME_AUTOSAY                 32252
#define ID_POPUP_FILE_CLOSE             32253
#define ID_POPUP_FILE_SAVE              32254
#define ID_FILE_SAVESELECTION           32255
#define ID_BTN_WORLDS_WORLD1            32257
#define ID_BTN_WORLDS_WORLD2            32258
#define ID_BTN_WORLDS_WORLD3            32259
#define ID_BTN_WORLDS_WORLD4            32260
#define ID_BTN_WORLDS_WORLD5            32261
#define ID_BTN_WORLDS_WORLD6            32262
#define ID_BTN_WORLDS_WORLD7            32263
#define ID_BTN_WORLDS_WORLD8            32264
#define ID_BTN_WORLDS_WORLD9            32265
#define ID_BTN_WORLDS_WORLD0            32266
#define ID_CONNECT_DISCONNECT           32267
#define ID_FIND_AGAIN_FORWARDS          32268
#define ID_FIND_AGAIN_BACKWARDS         32269
#define ID_MENUITEM32963                32270
#define ID_WEB_PAGE                     32271
#define ID_REPEAT_LAST_COMMAND          32272
#define ID_MENUITEM32966                32273
#define ID_MENUITEM32967                32274
#define ID_DISPLAY_GOTOURL              32275
#define ID_DISPLAY_SENDMAILTO           32276
#define ID_ALT_DOWNARROW                32277
#define ID_ALT_UPARROW                  32278
#define ID_MENUITEM32972                32279
#define ID_VIEW_RESET_TOOLBARS          32280
#define ID_CONFIGURE_NAME               32281
#define ID_CONFIGURE_APPEARANCE         32282
#define ID_CONFIGURE_INPUT              32283
#define ID_CONFIGURE_TRIGGERS           32284
#define ID_CONFIGURE_PASTE              32285
#define ID_CONFIGURE_SCRIPTING          32286
#define ID_HELP_MUDLISTS                32287
#define ID_KEYS_TAB                     32288
#define ID_CONNECTION_QUICK_CONNECT     32289
#define ID_GAME_RELOAD_SCRIPT_FILE      32290
#define ID_DISPLAY_CLEAR_OUTPUT         32291
#define ID_DISPLAY_STOPSOUNDPLAYING     32292
#define ID_HELP_BUGREPORTSUGGESTION     32293
#define ID_HELP_GETTINGSTARTED          32294
#define ID_GAME_CONFIGURE_MUDADDRESS    32295
#define ID_GAME_CONFIGURE_CONNECTION    32296
#define ID_GAME_CONFIGURE_LOGGING       32297
#define ID_GAME_CONFIGURE_INFO          32298
#define ID_GAME_CONFIGURE_NOTES         32299
#define ID_GAME_CONFIGURE_OUTPUT        32300
#define ID_GAME_CONFIGURE_COLOURS       32301
#define ID_GAME_CONFIGURE_HIGHLIGHTING  32302
#define ID_GAME_CONFIGURE_STRINGS       32303
#define ID_GAME_CONFIGURE_PRINTING      32304
#define ID_GAME_CONFIGURE_COMMANDS      32305
#define ID_GAME_CONFIGURE_KEYPAD        32306
#define ID_GAME_CONFIGURE_MACROS        32307
#define ID_GAME_CONFIGURE_AUTOSAY       32308
#define ID_GAME_CONFIGURE_PASTETOWORLD  32309
#define ID_GAME_CONFIGURE_SENDFILE      32310
#define ID_GAME_CONFIGURE_SCRIPTING     32311
#define ID_GAME_CONFIGURE_VARIABLES     32312
#define ID_GAME_CONFIGURE_TRIGGERS      32313
#define ID_GAME_CONFIGURE_ALIASES       32314
#define ID_GAME_CONFIGURE_TIMERS        32315
#define ID_GAME_RESETALLTIMERS          32316
#define ID_KEYS_ESCAPE                  32317
#define ID_DISPLAY_BOOKMARKSELECTION    32318
#define ID_DISPLAY_GOTOBOOKMARK         32319
#define ID_INPUT_GLOBALCHANGE           32320
#define ID_GAME_EDITSCRIPTFILE          32321
#define ID_VIEW_ALWAYSONTOP             32322
#define ID_EDIT_SPELLCHECK              32323
#define ID_DISPLAY_RECALLTEXT           32324
#define ID_GAME_SENDTOALLWORLDS         32325
#define ID_EDIT_GENERATECHARACTERNAME   32326
#define ID_EDIT_RELOADNAMESFILE         32327
#define ID_POPUP_COPYCOLOUR             32328
#define ID_POPUP_PASTECOLOUR            32329
#define ID_FILE_RELOADDEFAULTS          32330
#define ID_DISPLAY_TEXTATTRIBUTES       32331
#define ID_VIEW_FULLSCREENMODE          32332
#define ID_EDIT_NOTESWORKAREA           32333
#define ID_GAME_TRACE                   32334
#define ID_LOG_FILE_NAME                32335
#define IDS_CANNOT_BE_BLANK             32336
#define IDS_MIN_STRING_SIZE             32337
#define IDS_TOOLBAR                     32338
#define IDS_GAME_TOOLBAR                32339
#define IDS_ACTIVITY_TOOLBAR            32340
#define ID_CONNECTION_RECONNECTONDISCONNECT 32341
#define ID_POPUP_TIMECURRENTLINERECEIVED 32342
#define ID_DISPLAY_CLEAR_COMMAND_HISTORY 32343
#define ID_GAME_CONFIGURE_NAME_AND_PASSWORD 32344
#define ID_GAME_CONFIGURE_CUSTOM_COLOURS 32345
#define ID_ESCAPE                       32778
#define ID_VIEW_ACTIVITYTOOLBAR         32944
#define ID_EDIT_WORDWRAP                32945
#define ID_EDIT_GOTOMATCHINGBRACE       32946
#define ID_EDIT_SELECTTOMATCHINGBRACE   32947
#define ID_EDIT_SENDTOWORLD             32948
#define ID_EDIT_REFRESHRECALLEDDATA     32949
#define ID_WINDOW_CLOSEALLNOTEPADWINDOWS 32951
#define ID_EDIT_SENDTOCOMMANDWINDOW     32952
#define ID_EDIT_FLIPTONOTEPAD           32953
#define ID_FILE_OPENWORLDSINSTARTUPLIST 32954
#define ID_FILE_WINSOCK                 32955
#define ID_INPUT_DISCARDQUEUEDCOMMANDS  32956
#define ID_POPUP_SAVEWORLDDETAILSAS     32957
#define ID_GAME_MAPPER                  32958
#define ID_GAME_DOMAPPERSPECIAL         32959
#define ID_EDIT_INSERT                  32960
#define ID_EDIT_ASCIIART                32961
#define ID_POPUP_DELETETHIS             32962
#define ID_DISPLAY_GOTOLINE             32963
#define ID_FILE_CTRL_P                  -32572
#define ID_FILE_CTRL_N                  32965
#define ID_EDIT_CTRL_Z                  -32570
#define ID_DEBUG_WORLD_INPUT            32967
#define ID_EDIT_COLOURPICKER            32968
#define ID_DISPLAY_ECHOCOMMANDS         32969
#define ID_DISPLAY_NOCOMMANDECHO        32970
#define ID_EDIT_DEBUGINCOMINGPACKETS    32971
#define ID_GAME_CONFIGURE_MXPPUEBLO     32972
#define ID_REPEAT_LAST_WORD             32973
#define ID_EDIT_COPYASHTML              32974
#define ID_CONNECTION_CONNECTTOALLOPENWORLDS 32975
#define ID_CONNECTION_CONNECTTOWORLDSINSTARTUPLIST 32976
#define ID_CONVERT_QUOTEFORUMCODES      32977
#define ID_COMMAND_HOME                 32978
#define ID_COMMAND_END                  32979
#define ID_FILE_IMPORT                  32980
#define ID_CONVERT_BASE64ENCODE         32981
#define ID_CONVERT_BASE64DECODE         32982
#define ID_FILE_PLUGINS                 32983
#define ID_FILE_PLUGINWIZARD            32984
#define ID_GAME_DOMAPPERCOMMENT         32985
#define ID_HELP_FORUM                   32986
#define ID_HELP_FUNCTIONSWEBPAGE        32987
#define ID_VIEW_INFOBAR                 32988
#define ID_CONVERT_CONVERTHTMLSPECIAL   32989
#define ID_UNCONVERT_CONVERTHTMLSPECIAL 32990
#define ID_GAME_CHATSESSIONS            32991
#define ID_CTRL_KEYPAD_0                32992
#define ID_CTRL_KEYPAD_1                32993
#define ID_CTRL_KEYPAD_2                32994
#define ID_CTRL_KEYPAD_3                32995
#define ID_CTRL_KEYPAD_4                32996
#define ID_CTRL_KEYPAD_5                32997
#define ID_CTRL_KEYPAD_6                32998
#define ID_CTRL_KEYPAD_7                32999
#define ID_CTRL_KEYPAD_8                33000
#define ID_CTRL_KEYPAD_9                33001
#define ID_CTRL_KEYPAD_DOT              33002
#define ID_CTRL_KEYPAD_SLASH            33003
#define ID_CTRL_KEYPAD_STAR             33004
#define ID_CTRL_KEYPAD_DASH             33005
#define ID_CTRL_KEYPAD_PLUS             33006
#define ID_ALT_O                        33007
#define ID_ALT_K                        33008
#define ID_ALT_L                        33009
#define ID_ALT_M                        33010
#define ID_ALT_N                        33011
#define ID_ALT_V                        33012
#define ID_ALT_X                        33013
#define ID_ALT_Z                        33014
#define ID_ALT_R                        33015
#define ID_ALT_Q                        33016
#define ID_ALT_J                        33017
#define ID_ALT_A                        33018
#define ID_ALT_P                        33019
#define ID_ALT_S                        33020
#define ID_ALT_T                        33021
#define ID_ALT_U                        33022
#define ID_ALT_Y                        33023
#define ID_ALT_B                        33024
#define ID_GAME_CONFIGURE_CHAT          33025
#define ID_MACRO_F1                     33026
#define ID_MACRO_CTRL_F1                33027
#define ID_MACRO_SHIFT_F1               33028
#define ID_HELP_DOCUMENTATIONWEBPAGE    33029
#define ID_HELP_REGULAREXPRESSIONSWEBPAGE 33030
#define ID_POPUP_RESTORE                33031
#define ID_GAME_RESETCONNECTEDTIME      33032
#define ID_ACCEL33033                   33033
#define ID_HELP_PLUGINSLIST             33034
#define ID_EDIT_SENDTOIMMEDIATE         33035
#define ID_DISPLAY_HIGHLIGHTPHRASE      33036
#define ID_EDIT_GENERATEUNIQUEID        33037
#define ID_POPUP_CHARACTERCLASS_DELETEME 33039
#define ID_POPUP_QUANTIFIERS_DELETEME   33040
#define ID_POPUP_POSITION_DELETEME      33041
#define ID_POPUP_GROUPING_DELETEME      33042
#define ID_POPUP_ASSERTIONS_DELETEME    33043
#define ID_DISPLAY_MULTILINETRIGGER     33044
#define ID_POPUP_OPTIONS_DELETEME       33045
#define ID_GAME_FUNCTIONSLIST           33046
#define ID_SEARCH_GLOBALREPLACE         33047
#define ID_COMPLETE_FUNCTION            33048
#define ID_INPUT_KEYNAME                33049
#define ID_WINDOW_MAXIMIZE              33050
#define ID_WINDOW_RESTORE               33051
#define ID_EDIT_CONVERTCLIPBOARDFORUMCODES 33052
#define ID_POPUP_HELP                   33053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        361
#define _APS_NEXT_COMMAND_VALUE         33054
#define _APS_NEXT_CONTROL_VALUE         2897
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
